#!/usr/bin/env python3
"""Regenerate the PDF fixture embedded in tests/test_pdf_import.cpp.

The fixture is a deliberately minimal single-page PDF that exercises the
pdf2md.js heuristics: ATX headings (via font-size deltas), body paragraphs,
bold+italic emphasis, a Courier monospace code block, bullet and ordered lists,
a 2x3 pipe table, a cross-line hard-hyphen wrap, and a lone page-number footer.

It is hand-authored (boring PDF syntax: BT/ET text blocks over base-14 font
resources) SPECIFICALLY so nothing in the test depends on another subsystem
(e.g. the app's own PDF export). The base-14 font names are kept: pdf.js maps
them to real metrics without embedding font files. No fonts, images, or
compressed streams are involved, so the file is small and deterministic.

Usage:
    tests/gen_pdf_fixture.py            # print the PDF bytes (base64, one line)
    tests/gen_pdf_fixture.py --verify   # compare against kFixturePdfB64 in the test
"""

import base64
import re
import sys

# (font-resource, size, x, y, text). y is PDF user space, origin bottom-left;
# pdf.js getTextContent reports the same coordinates, tx/ty from transform[4]/[5].
TEXT_LINES = (
    ("/Helv-Bold", 24, 40, 700, "(Main Title)"),
    ("/Helv-Bold", 14, 40, 660, "(Section Heading)"),
    ("/Helv", 12, 40, 620, "(A normal body paragraph with several words to test wrapping.)"),
    ("/Helv", 12, 40, 596, "(Paragraph two of the section body text.)"),
    ("/Helv-Obl", 12, 40, 560, "(An emphasized fragment with bold inside.)"),
    ("/Cour", 10, 40, 520, "(def fib(n):)"),
    ("/Cour", 10, 72, 500, "(    return n)"),
    ("/Helv", 11, 40, 460, r"(\267 first bullet)"),
    ("/Helv", 11, 44, 440, r"(\267 second bullet)"),
    ("/Helv", 11, 40, 400, "(1. first item)"),
    ("/Helv", 11, 40, 380, "(2. second item)"),
    ("/Helv", 10, 80, 336, "(Column A)"),
    ("/Helv", 10, 240, 336, "(Column B)"),
    ("/Helv", 10, 80, 318, "(Value 1)"),
    ("/Helv", 10, 240, 318, "(Value 2)"),
    ("/Helv", 10, 80, 300, "(Value 3)"),
    ("/Helv", 10, 240, 300, "(Value 4)"),
    ("/Helv", 12, 40, 260, "(This line ends in a hard hyphen-)"),
    ("/Helv", 12, 40, 240, "(ation continuation.)"),
    ("/Helv", 8, 500, 40, "(Page 1)"),
)

CONTENT = "".join(
    "BT %s %d Tf %d %d Td %s Tj ET\n" % (f, s, x, y, t) for f, s, x, y, t in TEXT_LINES
).encode("latin-1")


def build_pdf():
    objs = []
    # Number -> bytes. Physical order in file: 1,2,3,4,5,6,7,8 (matching the
    # original fixture layout), with a valid xref table pointing at each.
    obj = {
        1: b"<< /Type /Catalog /Pages 2 0 R >>",
        2: b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        3: (b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
            b"/Resources << /Font << /Helv 5 0 R /Helv-Bold 6 0 R "
            b"/Helv-Obl 7 0 R /Cour 8 0 R >> >> /Contents 4 0 R >>"),
        4: b"<< /Length %d >>\nstream\n%b\nendstream" % (len(CONTENT), CONTENT),
        5: b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
        6: b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>",
        7: b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Oblique >>",
        8: b"<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>",
    }

    out = bytearray(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")
    offsets = {}
    for num in sorted(obj):
        offsets[num] = len(out)
        out += b"%d 0 obj\n" % num + obj[num] + b"\nendobj\n"

    xref_pos = len(out)
    out += b"xref\n0 9\n"
    out += b"0000000000 65535 f \n"
    for num in sorted(obj):
        out += b"%010d 00000 n \n" % offsets[num]

    out += b"trailer\n<< /Size 9 /Root 1 0 R >>\nstartxref\n%d\n%%%%EOF\n" % xref_pos
    return bytes(out)


PDF = build_pdf()


def embedded_b64():
    import os
    test_path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                             "test_pdf_import.cpp")
    src = open(test_path, encoding="utf-8").read()
    match = re.search(r"kFixturePdfB64 =\n(?:\"[^\"]*\"\n)+?\"[^\"]*\"\s*;", src)
    if not match:
        return None
    return "".join(re.findall(r"\"([^\"]*)\"", match.group(0)))


def main():
    if "--verify" in sys.argv:
        embedded = embedded_b64()
        if embedded is None:
            print("could not find kFixturePdfB64 in test file", file=sys.stderr)
            return 2
        generated = base64.b64encode(PDF).decode("ascii")
        if embedded == generated:
            print("verify: embedded kFixturePdfB64 matches generated bytes")
            return 0
        print("verify: MISMATCH (run without --verify to regenerate)", file=sys.stderr)
        print("embedded len %d, generated len %d" % (len(embedded), len(generated)),
              file=sys.stderr)
        return 1
    print(base64.b64encode(PDF).decode("ascii"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
