// Copyright (C) 2026 LazyArse
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
#include <gtest/gtest.h>
#include <QApplication>
#include <QByteArray>
#include <QTemporaryDir>
#include <QFile>
#include <QTextStream>

#include "TestConfig.h"
#include "PdfImporter.h"

// Deterministic PDF fixture (base-14 Helvetica family + Courier), generated by
// tests/gen_pdf_fixture.py. Exercises headings, body text, italic, a monospace
// code block, bullet + ordered lists, a 2x3 table and a cross-line hyphenated
// word, with baselines spaced far enough apart for the importer's y-gap
// heuristics to separate them cleanly.
static const char *kFixturePdfB64 =
"JVBERi0xLjQKJeLjz9MKMSAwIG9iago8PCAvVHlwZSAvQ2F0YWxvZyAvUGFnZXMgMiAwIFIgPj4K"
"ZW5kb2JqCjIgMCBvYmoKPDwgL1R5cGUgL1BhZ2VzIC9LaWRzIFszIDAgUl0gL0NvdW50IDEgPj4K"
"ZW5kb2JqCjQgMCBvYmoKPDwgL0xlbmd0aCAxMDQ2ID4+CnN0cmVhbQpCVCAvSGVsdi1Cb2xkIDI0"
"IFRmIDQwIDcwMCBUZCAoTWFpbiBUaXRsZSkgVGogRVQKQlQgL0hlbHYtQm9sZCAxNCBUZiA0MCA2"
"NjAgVGQgKFNlY3Rpb24gSGVhZGluZykgVGogRVQKQlQgL0hlbHYgMTIgVGYgNDAgNjIwIFRkIChB"
"IG5vcm1hbCBib2R5IHBhcmFncmFwaCB3aXRoIHNldmVyYWwgd29yZHMgdG8gdGVzdCB3cmFwcGlu"
"Zy4pIFRqIEVUCkJUIC9IZWx2IDEyIFRmIDQwIDU5NiBUZCAoUGFyYWdyYXBoIHR3byBvZiB0aGUg"
"c2VjdGlvbiBib2R5IHRleHQuKSBUaiBFVApCVCAvSGVsdi1PYmwgMTIgVGYgNDAgNTYwIFRkIChB"
"biBlbXBoYXNpemVkIGZyYWdtZW50IHdpdGggYm9sZCBpbnNpZGUuKSBUaiBFVApCVCAvQ291ciAx"
"MCBUZiA0MCA1MjAgVGQgKGRlZiBmaWIobik6KSBUaiBFVApCVCAvQ291ciAxMCBUZiA3MiA1MDAg"
"VGQgKCAgICByZXR1cm4gbikgVGogRVQKQlQgL0hlbHYgMTEgVGYgNDAgNDYwIFRkIChcMjY3IGZp"
"cnN0IGJ1bGxldCkgVGogRVQKQlQgL0hlbHYgMTEgVGYgNDQgNDQwIFRkIChcMjY3IHNlY29uZCBi"
"dWxsZXQpIFRqIEVUCkJUIC9IZWx2IDExIFRmIDQwIDQwMCBUZCAoMS4gZmlyc3QgaXRlbSkgVGog"
"RVQKQlQgL0hlbHYgMTEgVGYgNDAgMzgwIFRkICgyLiBzZWNvbmQgaXRlbSkgVGogRVQKQlQgL0hl"
"bHYgMTAgVGYgODAgMzM2IFRkIChDb2x1bW4gQSkgVGogRVQKQlQgL0hlbHYgMTAgVGYgMjQwIDMz"
"NiBUZCAoQ29sdW1uIEIpIFRqIEVUCkJUIC9IZWx2IDEwIFRmIDgwIDMxOCBUZCAoVmFsdWUgMSkg"
"VGogRVQKQlQgL0hlbHYgMTAgVGYgMjQwIDMxOCBUZCAoVmFsdWUgMikgVGogRVQKQlQgL0hlbHYg"
"MTAgVGYgODAgMzAwIFRkIChWYWx1ZSAzKSBUaiBFVApCVCAvSGVsdiAxMCBUZiAyNDAgMzAwIFRk"
"IChWYWx1ZSA0KSBUaiBFVApCVCAvSGVsdiAxMiBUZiA0MCAyNjAgVGQgKFRoaXMgbGluZSBlbmRz"
"IGluIGEgaGFyZCBoeXBoZW4tKSBUaiBFVApCVCAvSGVsdiAxMiBUZiA0MCAyNDAgVGQgKGF0aW9u"
"IGNvbnRpbnVhdGlvbi4pIFRqIEVUCkJUIC9IZWx2IDggVGYgNTAwIDQwIFRkIChQYWdlIDEpIFRq"
"IEVUCgplbmRzdHJlYW0KZW5kb2JqCjUgMCBvYmoKPDwgL1R5cGUgL0ZvbnQgL1N1YnR5cGUgL1R5"
"cGUxIC9CYXNlRm9udCAvSGVsdmV0aWNhID4+CmVuZG9iago2IDAgb2JqCjw8IC9UeXBlIC9Gb250"
"IC9TdWJ0eXBlIC9UeXBlMSAvQmFzZUZvbnQgL0hlbHZldGljYS1Cb2xkID4+CmVuZG9iago3IDAg"
"b2JqCjw8IC9UeXBlIC9Gb250IC9TdWJ0eXBlIC9UeXBlMSAvQmFzZUZvbnQgL0hlbHZldGljYS1P"
"YmxpcXVlID4+CmVuZG9iago4IDAgb2JqCjw8IC9UeXBlIC9Gb250IC9TdWJ0eXBlIC9UeXBlMSAv"
"QmFzZUZvbnQgL0NvdXJpZXIgPj4KZW5kb2JqCjMgMCBvYmoKPDwgL1R5cGUgL1BhZ2UgL1BhcmVu"
"dCAyIDAgUiAvTWVkaWFCb3ggWzAgMCA2MTIgNzkyXSAvUmVzb3VyY2VzIDw8IC9Gb250IDw8IC9I"
"ZWx2IDUgMCBSIC9IZWx2LUJvbGQgNiAwIFIgL0hlbHYtT2JsIDcgMCBSIC9Db3VyIDggMCBSID4+"
"ID4+IC9Db250ZW50cyA0IDAgUiA+PgplbmRvYmoKeHJlZgowIDkKMDAwMDAwMDAwMCA2NTUzNSBm"
"IAowMDAwMDAwMDE1IDAwMDAwIG4gCjAwMDAwMDAwNjQgMDAwMDAgbiAKMDAwMDAwMTUxMCAwMDAw"
"MCBuIAowMDAwMDAwMTIxIDAwMDAwIG4gCjAwMDAwMDEyMTkgMDAwMDAgbiAKMDAwMDAwMTI4OSAw"
"MDAwMCBuIAowMDAwMDAxMzY0IDAwMDAwIG4gCjAwMDAwMDE0NDIgMDAwMDAgbiAKdHJhaWxlcgo8"
"PCAvU2l6ZSA5IC9Sb290IDEgMCBSID4+CnN0YXJ0eHJlZgoxNjgzCiUlRU9GCg==";

static QString writeFixturePdf(QTemporaryDir &dir)
{
    const QByteArray bytes = QByteArray::fromBase64(kFixturePdfB64);
    const QString path = dir.filePath("fixture.pdf");
    QFile f(path);
    if (!f.open(QIODevice::WriteOnly)) return {};
    f.write(bytes);
    return path;
}

static QString norm(const QString &s)
{
    return s.simplified();
}

// The converter is fully offline (pdf.js + worker + pdf2md bundled as qrc
// resources inlined into a hidden page), so nothing here touches the network.
TEST(PdfImporter, StructuredDocumentBecomesMarkdown)
{
    QTemporaryDir dir;
    ASSERT_TRUE(dir.isValid());
    const QString path = writeFixturePdf(dir);
    ASSERT_FALSE(path.isEmpty());

    PdfImportResult res = PdfImporter::convert(path);
    ASSERT_TRUE(res.ok) << "error: " << res.error.toStdString();
    EXPECT_GT(res.pages, 0);

    const QString md = norm(res.markdown);
    // Title + section heading come out as ATX headings.
    EXPECT_NE(md, QString());
    EXPECT_TRUE(md.contains("Main Title")) << md.toStdString();
    EXPECT_TRUE(md.contains("Section Heading"));
    // Body paragraphs survive verbatim.
    EXPECT_TRUE(md.contains("A normal body paragraph with several words to test wrapping."));
    // Emphasized fragment keeps its *italic* markdown style.
    EXPECT_TRUE(md.contains("*An emphasized fragment with bold inside.*"));
    // Monospace run becomes a fenced code block with both lines. (norm()
    // simplifies whitespace, so the fence newlines collapse to spaces.)
    EXPECT_TRUE(md.contains("``` def fib(n): return n ```")) << md.toStdString();
    // Bullet and ordered lists.
    EXPECT_TRUE(md.contains("- first bullet"));
    EXPECT_TRUE(md.contains("- second bullet"));
    EXPECT_TRUE(md.contains("1. first item"));
    // Two-column table with header and two data rows.
    EXPECT_TRUE(md.contains("| Column A | Column B |"));
    EXPECT_TRUE(md.contains("| Value 1 | Value 2 |"));
    EXPECT_TRUE(md.contains("| Value 3 | Value 4 |"));
    // Cross-line hyphenation is rejoined without the break marker.
    EXPECT_TRUE(md.contains("This line ends in a hard hyphenation continuation."));
}

TEST(PdfImporter, MissingFileFailsGracefully)
{
    PdfImportResult res = PdfImporter::convert(QDir::tempPath() + "/no-such-file-xyz.pdf");
    EXPECT_FALSE(res.ok);
    EXPECT_FALSE(res.error.isEmpty());
}

TEST(PdfImporter, NonPdfFileFails)
{
    QTemporaryDir dir;
    ASSERT_TRUE(dir.isValid());
    const QString path = dir.filePath("garbage.pdf");
    QFile f(path);
    ASSERT_TRUE(f.open(QIODevice::WriteOnly | QIODevice::Text));
    f.write("this is definitely not a pdf document, just plain text");
    f.close();

    PdfImportResult res = PdfImporter::convert(path);
    EXPECT_FALSE(res.ok);
    EXPECT_FALSE(res.error.isEmpty());
}

int main(int argc, char **argv)
{
    QApplication app(argc, argv);
    setupTestConfig();
    testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}