// Copyright (C) 2026 LazyArse
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
#include "JsSnippets.h"
#include "StaticHelpers.h"

const QString mermaidInitJs = QStringLiteral(
    "function initMermaid(){"
    "var els=document.querySelectorAll('code.language-mermaid');"
    "if(!els.length)return Promise.resolve();"
    "els.forEach(function(el){"
    "var pre=el.parentElement;"
    "var line=pre&&pre.getAttribute('data-line')?pre.getAttribute('data-line'):'';"
    "var wrap=document.createElement('div');"
    "wrap.className='scriba-chart-wrap';"
    "if(line)wrap.setAttribute('data-line',line);"
    "pre.parentElement.replaceChild(wrap,pre);"
    "var div=document.createElement('div');"
    "div.className='mermaid';"
    "div.textContent=el.textContent;"
    "wrap.appendChild(div);"
    "});"
    "return mermaid.run({querySelector:'.mermaid'});"
    "}"
);

const QString headingIdJs = QStringLiteral(
    "function generateHeadingIds(){"
    "var used={};"
    "document.querySelectorAll('h1,h2,h3,h4,h5,h6').forEach(function(h){"
    "if(!h.id){"
    "var base=h.textContent.toLowerCase().replace(/[^\\w\\s-]/g,'').replace(/\\s+/g,'-').replace(/^-+|-+$/g,'');"
    "if(!base)return;"
    "var id=base,n=1;while(used[id])id=base+'-'+(n++);used[id]=true;h.id=id;"
    "}"
    "});"
    "}"
);

// Anchor navigation for `#heading` links. scribaScrollToSlug() slugifies the
// fragment the way generateHeadingIds() slugs headings and scrolls to the
// match; it returns whether the element was found. scribaScrollToSlugRetry()
// polls for up to ~6s (headings get their ids only after the heavy render
// pass) — safe for same-document jumps, where no page reload kills the
// closure. Cross-document jumps retry from C++ instead (a fresh page load
// discards in-flight JS).
const QString anchorNavJs = QString(
        "function scribaScrollToSlug(frag){"
        "try{"
        "var slug=decodeURIComponent(frag).toLowerCase().replace(/[^\\w\\s-]/g,'').replace(/\\s+/g,'-').replace(/^-+|-+$/g,'');"
        "var el=slug?document.getElementById(slug):null;"
        "if(el){el.scrollIntoView({block:'start',behavior:'auto'});return true;}"
        "}catch(e){}"
        "return false;"
        "}"
        "function scribaScrollToSlugRetry(frag){var tries=0;(function poll(){"
        "if(scribaScrollToSlug(frag)||tries++>20)return;setTimeout(poll,%1);"
        "})();}"
    ).arg(QString::number(JsTiming::AnchorNavRetry));

const QString katexInitJs = QStringLiteral(
    "function scribaRenderMath(){"
    "if(typeof katex==='undefined')return;"
    "document.querySelectorAll('span.katex[data-tex]').forEach(function(el){"
    "if(el.getAttribute('data-rendered'))return;"
    "var disp=el.parentElement&&el.parentElement.classList.contains('katex-display');"
    "try{"
    "katex.render(el.getAttribute('data-tex'),el,{displayMode:!!disp,throwOnError:false});"
    "}catch(e){"
    "el.textContent=el.getAttribute('data-tex');"
    "}"
    "el.setAttribute('data-rendered','1');"
    "});"
    "}"
    "function initKaTeX(){"
    "if(typeof katex==='undefined')return;"
    "scribaMathEditPass();"
    "scribaRenderMath();"
    "}"
);

const QString echartsInitJs = QString(
    "function initECharts(){"
    "var els=document.querySelectorAll('code.language-ec');"
    "if(!els.length)return Promise.resolve();"
    "return Promise.all(Array.from(els).map(function(el){"
    "try{"
    "var spec=JSON.parse(el.textContent);"
    "var container=el.parentElement;"
    "var line=container&&container.getAttribute('data-line')?container.getAttribute('data-line'):'';"
    "var wrap=document.createElement('div');"
    "wrap.className='scriba-chart-wrap';"
    "if(line)wrap.setAttribute('data-line',line);"
    "container.parentElement.replaceChild(wrap,container);"
    "var div=document.createElement('div');"
    "div.className='echarts-chart';"
    "div.style.width='100%';"
    "div.style.minHeight='300px';"
    "div.style.overflow='visible';"
    "wrap.appendChild(div);"
    "return new Promise(function(resolve){"
    "var tries=0;"
    "(function go(){"
    "if(div.clientWidth>0||++tries>%1){"
    "var chart=echarts.init(div,null,{renderer:'svg'});"
    "try{chart.setOption(spec);}catch(e){}"
    "chart.on('finished',function(){resolve(chart);});"
    "setTimeout(function(){resolve(chart);},%2);"
    "}else{setTimeout(go,%3);}"
    "})();"
    "});"
    "}"
    "catch(e){return Promise.resolve();}"
    "}));"
    "}"
    ).arg(QString::number(JsTiming::ChartLayoutTries),
          QString::number(JsTiming::EChartsReadyTimeout),
          QString::number(JsTiming::ChartLayoutPoll));

const QString chartEditJs = QStringLiteral(
    "function scribaEditAnchor(kind,line,idx,tex){"
    "var a=document.createElement('a');"
    "a.className='scriba-edit-btn';"
    "a.href='#scriba-edit:'+kind+':'+line+':'+idx+(tex?':'+encodeURIComponent(tex):'');"
    "a.textContent='\\u270e';"
    "a.title='Edit';"
    "return a;"
    "}"
    "function scribaMathEditPass(){"
    "var content=document.getElementById('scriba-content');"
    "if(!content)return;"
    "var lastLine=-1,idxInLine=0;"
    "Array.prototype.slice.call(content.querySelectorAll('span.katex[data-tex]')).forEach(function(el){"
    "if(el.getAttribute('data-editbox'))return;"
    "el.setAttribute('data-editbox','1');"
    "var lineS=el.getAttribute('data-line');"
    "var line=lineS?parseInt(lineS,10):0;"
    "if(line!==lastLine){lastLine=line;idxInLine=0;}"
    "var disp=el.parentElement&&el.parentElement.classList.contains('katex-display');"
    "var box=document.createElement('span');"
    "box.className='scriba-mathbox';"
    "box.style.display=disp?'block':'inline-block';"
    "el.parentNode.insertBefore(box,el);"
    "box.appendChild(el);"
    "box.appendChild(scribaEditAnchor('math',line,idxInLine++,el.getAttribute('data-tex')));"
    "});"
    "}"
);

const QString setImgTitlesJs = QStringLiteral(
    "function setImgTitles(){"
    "document.querySelectorAll('img:not([title])').forEach(function(img){"
    "if(img.alt)img.title=img.alt;"
    "});"
    "}"
);

// Footnote reference links get the text of their definition as a native title
// tooltip, so hovering `<sup><a href="#fn-N">` shows the note. The definition
// is cloned and its backref (`↶`) removed before reading the text.
const QString setFootnoteTitlesJs = QStringLiteral(
    "function setFootnoteTitles(){"
    "document.querySelectorAll('a[href^=\"#fn-\"]').forEach(function(a){"
    "var m=/^#fn-(\\d+)$/.exec(a.getAttribute('href'));"
    "if(!m)return;"
    "var li=document.getElementById('fn-'+m[1]);"
    "if(!li)return;"
    "var cl=li.cloneNode(true);"
    "cl.querySelectorAll('.footnote-backref').forEach(function(b){b.remove();});"
    "var t=(cl.innerText||cl.textContent||'').replace(/\\s+/g,' ').replace(/^\\s+|\\s+$/g,'');"
    "if(t)a.title=t;"
    "});"
    "}"
);

const QString katexToImageJs = QStringLiteral(
    "function convertKatexToImages(){"
    "var elements=document.querySelectorAll('.katex');"
    "if(!elements.length)return Promise.resolve();"
    "var cssText='';"
    "try{"
    "for(var si=0;si<document.styleSheets.length;si++){"
    "try{"
    "var rules=document.styleSheets[si].cssRules;"
    "for(var ri=0;ri<rules.length;ri++){"
    "var s=rules[ri].selectorText||'';"
    "if(s&&s.indexOf('katex')!==-1){"
    "cssText+=rules[ri].cssText+'\\n';"
    "}"
    "}"
    "}catch(e2){}"
    "}"
    "}catch(e1){}"
    "var promises=[];"
    "elements.forEach(function(el){"
    "var promise=new Promise(function(resolve){"
    "try{"
    "var rect=el.getBoundingClientRect();"
    "if(rect.width<1||rect.height<1){"
    "var span=document.createElement('span');"
    "span.textContent=el.textContent;"
    "el.parentNode.replaceChild(span,el);"
    "resolve();return;"
    "}"
    "var canvas=document.createElement('canvas');"
    "var scale=3.125;"   // 300 DPI fallback raster (300/96)
    "canvas.width=Math.ceil(rect.width*scale);"
    "canvas.height=Math.ceil(rect.height*scale);"
    "var ctx=canvas.getContext('2d');"
    "ctx.scale(scale,scale);"
    "var clone=el.cloneNode(true);"
    "clone.querySelectorAll('svg').forEach(function(svg){"
    "try{"
    "var ser=new XMLSerializer();"
    "var s=ser.serializeToString(svg);"
    "var img=document.createElement('img');"
    "img.src='data:image/svg+xml;base64,'+btoa(unescape(encodeURIComponent(s)));"
    "var sr=svg.getBoundingClientRect();"
    "img.width=Math.max(1,Math.round(sr.width));"
    "img.height=Math.max(1,Math.round(sr.height));"
    "img.style.verticalAlign='middle';"
    "svg.parentNode.replaceChild(img,svg);"
    "}catch(e){}"
    "});"
    "var data='<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"'+rect.width+'\" height=\"'+rect.height+'\">'"
    "+'<foreignObject width=\"100%\" height=\"100%\">'"
    "+'<div xmlns=\"http://www.w3.org/1999/xhtml\">'"
    "+(cssText?'<style>'+cssText+'</style>':'')"
    "+clone.outerHTML"
    "+'</div>'"
    "+'</foreignObject></svg>';"
    "var img=new Image();"
    "img.onload=function(){"
    "try{"
    "ctx.drawImage(img,0,0);"
    "var dataUrl=canvas.toDataURL('image/png');"
    "var imgEl=document.createElement('img');"
    "imgEl.src=dataUrl;"
    "imgEl.width=Math.round(rect.width);"    // CSS px → 96-DPI extent in HtmlToOoxml
    "imgEl.height=Math.round(rect.height);"
    "imgEl.style.verticalAlign='middle';"
    "el.parentNode.replaceChild(imgEl,el);"
    "resolve();"
    "}catch(e){"
    "var span=document.createElement('span');"
    "span.textContent=el.textContent;"
    "el.parentNode.replaceChild(span,el);"
    "resolve();"
    "}"
    "};"
    "img.onerror=function(){"
    "var span=document.createElement('span');"
    "span.textContent=el.textContent;"
    "el.parentNode.replaceChild(span,el);"
    "resolve();"
    "};"
    "img.src='data:image/svg+xml;base64,'+btoa(unescape(encodeURIComponent(data)));"
    "}catch(e){"
    "var span=document.createElement('span');"
    "span.textContent=el.textContent;"
    "el.parentNode.replaceChild(span,el);"
    "resolve();"
    "}"
    "});"
    "promises.push(promise);"
    "});"
    "return Promise.all(promises);"
    "}"
);

// Lightbox for preview image links. scribaShowImage() renders `href` in a
// full-window overlay; a backdrop click, the × button, or Escape closes it.
// The overlay lives outside #scriba-content, so live re-renders leave it
// open. Displaying the file as an <img> is safe even for SVG: scripts do not
// run in an image context.
const QString imageOverlayJs = QStringLiteral(
    "function scribaShowImage(href){"
    "var ov=document.getElementById('scriba-image-overlay');"
    "if(!ov){"
    "ov=document.createElement('div');"
    "ov.id='scriba-image-overlay';"
    "var box=document.createElement('div');"
    "box.className='scriba-image-box';"
    "var img=document.createElement('img');"
    "img.className='scriba-image-view';"
    "img.alt='';"
    "var cap=document.createElement('div');"
    "cap.className='scriba-image-caption';"
    "var close=document.createElement('button');"
    "close.type='button';"
    "close.className='scriba-image-close';"
    "close.title='Close (Esc)';"
    "close.textContent='\\u00d7';"
    "box.appendChild(img);"
    "box.appendChild(cap);"
    "box.appendChild(close);"
    "ov.appendChild(box);"
    "document.body.appendChild(ov);"
    "ov.addEventListener('click',function(e){if(e.target===ov)scribaHideImage();});"
    "close.addEventListener('click',function(e){e.stopPropagation();scribaHideImage();});"
    "document.addEventListener('keydown',function(e){if(e.key==='Escape')scribaHideImage();});"
    "}"
    "var img=ov.querySelector('img');"
    "img.src=href;"
    "var name=href;"
    "try{name=decodeURIComponent(href.split('/').pop()||href);}catch(e){}"
    "ov.querySelector('.scriba-image-caption').textContent=name;"
    "ov.style.display='flex';"
    "}"
    "function scribaHideImage(){"
    "var ov=document.getElementById('scriba-image-overlay');"
    "if(ov)ov.style.display='none';"
    "}"
);

// Stock chart engine adapters (Lightweight Charts + KlineCharts; TradeX was
// dropped — its talib.wasm cannot load via fetch() from qrc, see gotchas).
// The dialog emits a one-line dispatcher call whose JSON payload carries the
// fully precomputed indicator arrays (C++ Indicators module) — the engines
// only plot; no indicator math runs in JS. Lazy script injection keeps the
// engines out of pages that have no stock chart fence.
const QString stockChartsInitJs = QString(
    "window._scribaJsErrors=window._scribaJsErrors||[];"
    "window.addEventListener('error',function(e){window._scribaJsErrors.push(String(e.message));});"
    "function scribaLoadStockEngine(engine){"
    "var urls={lightweight:'qrc:///lightweight-charts.standalone.production.js',"
    "klinecharts:'qrc:///klinecharts.min.js'};"
    "var url=urls[engine];"
    "if(!url)return Promise.reject(new Error('unknown stock engine '+engine));"
    "var loaded=window._scribaStockEngines||(window._scribaStockEngines={});"
    "if(loaded[engine])return Promise.resolve();"
    "return new Promise(function(resolve,reject){"
    "var s=document.createElement('script');"
    "s.src=url;"
    "s.onload=function(){loaded[engine]=true;resolve();};"
    "s.onerror=function(){reject(new Error('failed to load '+url));};"
    "document.head.appendChild(s);"
    "});"
    "}"
    // KlineCharts custom-indicator factory: plots precomputed arrays (one
    // value per index; null/NaN entries are skipped by the engine).
    "function scribaKcIndicator(name,shortName,keys,arrays){"
    "return {"
    "name:name,shortName:shortName,series:'price',"
    "figures:keys.map(function(k){return {key:k,title:k,type:'line'};}),"
    "calc:function(dataList,ind){"
    "var e=ind.extendData;"
    "return dataList.map(function(d,i){"
    "var o={};"
    "for(var j=0;j<keys.length;j++){var a=e?e[j]:null;o[keys[j]]=a?a[i]:null;}"
    "return o;"
    "});"
    "},"
    "extendData:arrays"
    "};"
    "}"
    "function scribaRenderKlinecharts(el,opts){"
    "var chart=klinecharts.init(el);"
    "var data=opts.dates.map(function(d,i){"
    "var r=opts.ohlc[i];"
    "return {timestamp:Date.parse(d),open:r[0],high:r[3],low:r[2],close:r[1],"
    "volume:opts.volume&&opts.volumes?opts.volumes[i]:undefined};"
    "});"
    "chart.applyNewData(data);"
    "var st={};"
    "if(opts.type==='bar')st.candle={type:'candle_stroke'};"
    "else if(opts.type==='area')st.candle={type:'area'};"
    "else if(opts.type==='line'){"
    "st.candle={type:'candle_stroke',bar:{upColor:'rgba(0,0,0,0)',downColor:'rgba(0,0,0,0)',noChangeColor:'rgba(0,0,0,0)'}};"
    "}"
    "if(Object.keys(st).length)chart.setStyles(st);"
    "if(opts.type==='line'){"
    "chart.createIndicator({name:'SCRIBA_CLOSE',shortName:'Close',series:'price',"
    "figures:[{key:'c',title:'Close',type:'line'}],"
    "calc:function(list){return list.map(function(d){return {c:d.close};});}},"
    "true,{id:'candle_pane'});"
    "}"
    "var ind=opts.indicators||{};"
    "(opts.ma||[]).forEach(function(p){"
    "var arr=ind['ma'+p];"
    "if(arr)chart.createIndicator(scribaKcIndicator('SCRIBA_MA'+p,'MA'+p,['v'],[arr]),true,{id:'candle_pane'});"
    "});"
    "if(ind.boll){"
    "var b=ind.boll;"
    "chart.createIndicator(scribaKcIndicator('SCRIBA_BOLL','BOLL',['upper','mid','lower'],"
    "[b.upper,b.mid,b.lower]),true,{id:'candle_pane'});"
    "}"
    "if(ind.macd){"
    "var m=ind.macd;"
    "chart.createIndicator(scribaKcIndicator('SCRIBA_MACD','MACD',['diff','dea','hist'],"
    "[m.diff,m.dea,m.hist]));"
    "}"
    "if(ind.rsi){"
    "chart.createIndicator(scribaKcIndicator('SCRIBA_RSI','RSI',['v'],[ind.rsi]));"
    "}"
    "if(ind.kdj){"
    "var k=ind.kdj;"
    "chart.createIndicator(scribaKcIndicator('SCRIBA_KDJ','KDJ',['k','d','j'],"
    "[k.k,k.d,k.j]));"
    "}"
    "if(opts.volume)chart.createIndicator('VOL');"
    "return chart;"
    "}"
    "function scribaAddLine(chart,times,arr,color,paneIndex){"
    "if(!arr)return;"
    "var opts={color:color,lineWidth:1,priceLineVisible:false,lastValueVisible:false};"
    "if(paneIndex)opts.paneIndex=paneIndex;"
    "var s=chart.addSeries(LightweightCharts.LineSeries,opts);"
    "var pts=[];"
    "arr.forEach(function(v,i){if(v!==null&&v!==undefined)pts.push({time:times[i],value:v});});"
    "if(pts.length)s.setData(pts);"
    "}"
    "function scribaRenderLightweight(el,opts){"
    "var chart=LightweightCharts.createChart(el,{"
    "layout:{background:{type:'solid',color:'transparent'}},"
    "timeScale:{timeVisible:true}"
    "});"
    "var times=opts.dates.map(function(d){return Math.round(Date.parse(d)/1000);});"
    "var main;"
    "if(opts.type==='bar')main=chart.addSeries(LightweightCharts.BarSeries,{});"
    "else if(opts.type==='line')main=chart.addSeries(LightweightCharts.LineSeries,{});"
    "else if(opts.type==='area')main=chart.addSeries(LightweightCharts.AreaSeries,{});"
    "else main=chart.addSeries(LightweightCharts.CandlestickSeries,{});"
    "if(opts.type==='candlestick'||opts.type==='bar'){"
    "main.setData(opts.ohlc.map(function(r,i){"
    "return {time:times[i],open:r[0],high:r[3],low:r[2],close:r[1]};}));"
    "}else{"
    "main.setData(opts.ohlc.map(function(r,i){return {time:times[i],value:r[1]};}));"
    "}"
    "var ind=opts.indicators||{};"
    "(opts.ma||[]).forEach(function(p,i){"
    "scribaAddLine(chart,times,ind['ma'+p],['#e0a53a','#3a9be0','#7b5cd6','#35c26b'][i%4],0);"
    "});"
    "if(ind.boll){"
    "scribaAddLine(chart,times,ind.boll.upper,'#c26b7b',0);"
    "scribaAddLine(chart,times,ind.boll.mid,'#7bc26b',0);"
    "scribaAddLine(chart,times,ind.boll.lower,'#c26b7b',0);"
    "}"
    "if(opts.volume&&opts.volumes){"
    "chart.addPane();"
    "var vol=chart.addSeries(LightweightCharts.HistogramSeries,{"
    "priceFormat:{type:'volume'},priceLineVisible:false,lastValueVisible:false,paneIndex:1});"
    "var vd=[];"
    "opts.volumes.forEach(function(v,i){if(v!==null)vd.push({time:times[i],value:v});});"
    "vol.setData(vd);"
    "}"
    "if(ind.macd||ind.rsi||ind.kdj){"
    "chart.addPane();"
    "if(ind.macd){"
    "var m=ind.macd;"
    "scribaAddLine(chart,times,m.diff,'#e0a53a',2);"
    "scribaAddLine(chart,times,m.dea,'#3a9be0',2);"
    "var hist=chart.addSeries(LightweightCharts.HistogramSeries,{"
    "priceLineVisible:false,lastValueVisible:false,paneIndex:2});"
    "var hd=[];"
    "m.hist.forEach(function(v,i){if(v!==null)hd.push({time:times[i],value:v});});"
    "hist.setData(hd);"
    "}"
    "if(ind.rsi)scribaAddLine(chart,times,ind.rsi,'#35c26b',2);"
    "if(ind.kdj){"
    "var k=ind.kdj;"
    "scribaAddLine(chart,times,k.k,'#e0a53a',2);"
    "scribaAddLine(chart,times,k.d,'#3a9be0',2);"
    "scribaAddLine(chart,times,k.j,'#c26b7b',2);"
    "}"
    "}"
    "chart.timeScale().fitContent();"
    "return chart;"
    "}"
    "function initStockCharts(){"
    "var els=document.querySelectorAll('code.language-lc,code.language-kc');"
    "if(!els.length)return Promise.resolve();"
    "return Promise.all(Array.from(els).map(function(el){"
    "try{"
    "var body=el.textContent.replace(/^\\s+|\\s+$/g,'');"
    "var m=/^scribaStockChart\\(\\s*\"(\\w+)\"\\s*,\\s*(\\{.*\\})\\s*\\)\\s*$/.exec(body);"
    "if(!m)return Promise.resolve();"
    "var engine=m[1];"
    "var opts=JSON.parse(m[2]);"
    "var container=el.parentElement;"
    "var line=container&&container.getAttribute('data-line')?container.getAttribute('data-line'):'';"
    "var wrap=document.createElement('div');"
    "wrap.className='scriba-chart-wrap';"
    "if(line)wrap.setAttribute('data-line',line);"
    "container.parentElement.replaceChild(wrap,container);"
    "var btn=document.createElement('a');"
    "btn.className='scriba-edit-btn';"
    "btn.href='#scriba-edit:'+engine+':0:0:'+encodeURIComponent(body);"
    "btn.textContent='\\u270e';"
    "btn.title='Edit';"
    "wrap.appendChild(btn);"
    "var title=document.createElement('div');"
    "title.className='scriba-chart-title';"
    "title.style.cssText='font-weight:600;margin:0 0 4px;';"
    "title.textContent=opts.title||'';"
    "wrap.appendChild(title);"
    "var div=document.createElement('div');"
    "div.className='stock-chart';"
    "div.style.width='100%';"
    "div.style.minHeight='300px';"
    "wrap.appendChild(div);"
    "return new Promise(function(resolve){"
    "scribaLoadStockEngine(engine).then(function(){"
    "var tries=0;"
    "(function go(){"
    "if(div.clientWidth>0||++tries>%1){"
    "try{"
    "window._scribaStockDiag={w:div.clientWidth,h:div.clientHeight,tries:tries};"
    "if(engine==='lightweight')scribaRenderLightweight(div,opts);"
    "else scribaRenderKlinecharts(div,opts);"
    "}catch(e){window._scribaStockDiagError=String(e.message);}"
    "resolve();"
    "}else{setTimeout(go,%3);}"
    "})();"
    "},function(e){window._scribaStockLoadError=String(e.message);resolve();});"
    "});"
    "}"
    "catch(e){return Promise.resolve();}"
    "}));"
    "}"
    "function convertStockChartsToImages(){"
    "var charts=document.querySelectorAll('.scriba-chart-wrap canvas');"
    "if(!charts.length)return Promise.resolve();"
    "return Promise.all(Array.from(charts).map(function(cv){"
    "return new Promise(function(resolve){"
    "try{"
    "var rect=cv.getBoundingClientRect();"
    "if(rect.width<1||rect.height<1){resolve();return;}"
    "var scale=3.125;"
    "var out=document.createElement('canvas');"
    "out.width=Math.ceil(rect.width*scale);"
    "out.height=Math.ceil(rect.height*scale);"
    "var ctx=out.getContext('2d');"
    "ctx.scale(scale,scale);"
    "ctx.drawImage(cv,0,0,rect.width,rect.height);"
    "var img=document.createElement('img');"
    "img.src=out.toDataURL('image/png');"
    "img.width=Math.round(rect.width);"
    "img.height=Math.round(rect.height);"
    "cv.parentNode.replaceChild(img,cv);"
    "resolve();"
    "}catch(e){resolve();}"
    "});"
    "}));"
    "}"
    ).arg(QString::number(JsTiming::ChartLayoutTries),
          QString::number(JsTiming::ChartLayoutPoll),
          QString::number(JsTiming::ChartLayoutPoll));
